indentation fixed

diff --git a/encfsui b/encfsui
--- a/encfsui
+++ b/encfsui
@@ -67,9 +67,9 @@ gui() {
     local text="$3"
 
     if [[ $type == entry ]]; then
-	args="--hide-text"
+        args="--hide-text"
     else
-	args="--ellipsize --"
+        args="--ellipsize --"
     fi
 
     # Send errors to null to avoid spurious GTK warnings.
@@ -88,8 +88,8 @@ if mount | grep -q "^encfs on $tgt "; then
 
     # Prompt to unmount
     if ! gui Mount question \
-	"$tgt is already mounted.\n\nDo you want to unmount it?"; then
-	exit 0
+    "$tgt is already mounted.\n\nDo you want to unmount it?"; then
+        exit 0
     fi
 
     # Unmount it
@@ -97,20 +97,20 @@ if mount | grep -q "^encfs on $tgt "; then
 
     # Output an error if the unmount failed
     if [[ $? -ne 0 ]]; then
-		# Prompt to unmount
-	    if ! gui Mount question \
-			"$res\n\nDo you want to force unmount?"; then
-			exit 1
-	    fi
+        # Prompt to unmount
+        if ! gui Mount question \
+        "$res\n\nDo you want to force unmount?"; then
+            exit 1
+        fi
 
-		# force unmount it
-		res=$(fusermount -uz "$tgt" 2>&1)
-		
-		# Output an error if the unmount failed
-    	if [[ $? -ne 0 ]]; then
-			gui Unmount error "$res"
-			exit 1
-		fi
+        # force unmount it
+        res=$(fusermount -uz "$tgt" 2>&1)
+
+        # Output an error if the unmount failed
+        if [[ $? -ne 0 ]]; then
+            gui Unmount error "$res"
+            exit 1
+        fi
     fi
 
     # Remove target dir if it is empty
@@ -143,23 +143,23 @@ while true; do
     # option. That's why we are calling zenity and encfs
     # explicity ourselves.
     if [[ $? -ne 0 ]]; then
-	break
+        break
     fi
 
-	# Create target dir if it doesn't exist
-	mkdir -p "$tgt" &>/dev/null
+    # Create target dir if it doesn't exist
+    mkdir -p "$tgt" &>/dev/null
 
     # Give passphrase to encfs and mount the file system
     res=$(echo "$res" | encfs -S $PUBLIC $MINS "$src" "$tgt" 2>&1)
 
     # Check for error (typically a bad passphrase)
     if [[ $? -eq 0 ]]; then
-	if [[ $NOOPEN -eq 0 ]]; then
-	    open-dir-gui "$tgt"
-	fi
+        if [[ $NOOPEN -eq 0 ]]; then
+            open-dir-gui "$tgt"
+        fi
 
-	mounted=1
-	break
+        mounted=1
+        break
     fi
 
     gui Mount error "$res"
